version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_DB: goapi
      POSTGRES_USER: sing
      POSTGRES_PASSWORD: 12345678
    restart: always
    ports:
      - 5432:5432
      # volumes:
      # - ./_data:/var/lib/postgresql/data
      # adminer:
      #   image: adminer
      #   restart: always
      #   ports:
      #     - 8080:8080
  webapi:
    build: .
    image: sing3demons/assessment
    restart: always
    ports:
      - 2565:2565
    environment:
      - PORT=2565
      - DATABASE_URL=host=db port=5432 user=sing password=12345678 dbname=goapi sslmode=disable
    depends_on:
      - db
